ERROR - 2024-01-01 08:54:16 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\new xampp\htdocs\b2b\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\new xampp\htdocs\b2b\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'b2b', 3306, '', 0)
#1 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\new xampp\htdocs\b2b\app\Models\usersModel.php(20): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\new xampp\htdocs\b2b\app\Controllers\Home.php(26): App\Models\usersModel->isvalidate('1', '1')
#6 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(919): App\Controllers\Home->login()
#7 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\new xampp\htdocs\b2b\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\new xampp\htdocs\b2b\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\new xampp\htdocs\b2b\app\Models\usersModel.php(20): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\new xampp\htdocs\b2b\app\Controllers\Home.php(26): App\Models\usersModel->isvalidate('1', '1')
#5 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(919): App\Controllers\Home->login()
#6 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\new xampp\htdocs\b2b\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-01-01 08:54:16 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `userName` = :userName:
AND `password` = :password:', [...], false)
 3 APPPATH\Models\usersModel.php(20): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(26): App\Models\usersModel->isvalidate('1', '1')
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Home->login()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 08:55:18 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\new xampp\htdocs\b2b\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\new xampp\htdocs\b2b\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'b2b', 3306, '', 0)
#1 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\new xampp\htdocs\b2b\app\Models\usersModel.php(20): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\new xampp\htdocs\b2b\app\Controllers\Home.php(26): App\Models\usersModel->isvalidate('1', '1')
#6 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(919): App\Controllers\Home->login()
#7 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\new xampp\htdocs\b2b\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\new xampp\htdocs\b2b\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\new xampp\htdocs\b2b\app\Models\usersModel.php(20): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\new xampp\htdocs\b2b\app\Controllers\Home.php(26): App\Models\usersModel->isvalidate('1', '1')
#5 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(919): App\Controllers\Home->login()
#6 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\new xampp\htdocs\b2b\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-01-01 08:55:18 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `userName` = :userName:
AND `password` = :password:', [...], false)
 3 APPPATH\Models\usersModel.php(20): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(26): App\Models\usersModel->isvalidate('1', '1')
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Home->login()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 08:55:22 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\new xampp\htdocs\b2b\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\new xampp\htdocs\b2b\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'b2b', 3306, '', 0)
#1 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\new xampp\htdocs\b2b\app\Models\usersModel.php(20): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\new xampp\htdocs\b2b\app\Controllers\Home.php(26): App\Models\usersModel->isvalidate('1', '1')
#6 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(919): App\Controllers\Home->login()
#7 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\new xampp\htdocs\b2b\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\new xampp\htdocs\b2b\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\new xampp\htdocs\b2b\app\Models\usersModel.php(20): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\new xampp\htdocs\b2b\app\Controllers\Home.php(26): App\Models\usersModel->isvalidate('1', '1')
#5 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(919): App\Controllers\Home->login()
#6 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\new xampp\htdocs\b2b\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-01-01 08:55:22 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `userName` = :userName:
AND `password` = :password:', [...], false)
 3 APPPATH\Models\usersModel.php(20): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(26): App\Models\usersModel->isvalidate('1', '1')
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Home->login()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 09:54:27 --> mysqli_sql_exception: Unknown column 'rto_exp' in 'where clause' in C:\xampp\new xampp\htdocs\b2b\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\new xampp\htdocs\b2b\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\new xampp\htdocs\b2b\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\new xampp\htdocs\b2b\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\new xampp\htdocs\b2b\app\Controllers\Admin.php(1216): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(919): App\Controllers\Admin->rto_list()
#8 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#9 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\new xampp\htdocs\b2b\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-01-01 09:54:27 --> Unknown column 'rto_exp' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `transport_entry`
WHERE `rto_exp` >= :rto_exp:', [...], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Admin.php(1216): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Admin->rto_list()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 11:13:34 --> mysqli_sql_exception: Column 'rgn_date' cannot be null in C:\xampp\new xampp\htdocs\b2b\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\new xampp\htdocs\b2b\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ve...', 0)
#1 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ve...')
#2 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ve...')
#3 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ve...', Array, false)
#4 C:\xampp\new xampp\htdocs\b2b\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\new xampp\htdocs\b2b\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\new xampp\htdocs\b2b\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\new xampp\htdocs\b2b\app\Controllers\Admin.php(103): CodeIgniter\Model->insert(Array)
#8 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(919): App\Controllers\Admin->addvehicle()
#9 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#10 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\new xampp\htdocs\b2b\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-01-01 11:13:34 --> Column 'rgn_date' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `vehicle` (`name`, `rgn_date`, `iddate`, `type`, `number`, `user`, `spi_code`, `rto_exp`, `puc_exp`, `permit_exp`, `insurance_exp`, `fitness_exp`) VALUES (:name:, :rgn_date:, :iddate:, :type:, :number:, :user:, :spi_code:, :rto_exp:, :puc_exp:, :permit_exp:, :insurance_exp:, :fitness_exp:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Admin.php(103): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Admin->addvehicle()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 11:14:22 --> mysqli_sql_exception: Column 'rgn_date' cannot be null in C:\xampp\new xampp\htdocs\b2b\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\new xampp\htdocs\b2b\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ve...', 0)
#1 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ve...')
#2 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ve...')
#3 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ve...', Array, false)
#4 C:\xampp\new xampp\htdocs\b2b\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\new xampp\htdocs\b2b\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\new xampp\htdocs\b2b\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\new xampp\htdocs\b2b\app\Controllers\Admin.php(103): CodeIgniter\Model->insert(Array)
#8 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(919): App\Controllers\Admin->addvehicle()
#9 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#10 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\new xampp\htdocs\b2b\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-01-01 11:14:22 --> Column 'rgn_date' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `vehicle` (`name`, `rgn_date`, `iddate`, `type`, `number`, `user`, `spi_code`, `rto_exp`, `puc_exp`, `permit_exp`, `insurance_exp`, `fitness_exp`) VALUES (:name:, :rgn_date:, :iddate:, :type:, :number:, :user:, :spi_code:, :rto_exp:, :puc_exp:, :permit_exp:, :insurance_exp:, :fitness_exp:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Admin.php(103): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Admin->addvehicle()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-01 11:14:47 --> mysqli_sql_exception: Column 'rgn_date' cannot be null in C:\xampp\new xampp\htdocs\b2b\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\new xampp\htdocs\b2b\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ve...', 0)
#1 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ve...')
#2 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ve...')
#3 C:\xampp\new xampp\htdocs\b2b\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ve...', Array, false)
#4 C:\xampp\new xampp\htdocs\b2b\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\new xampp\htdocs\b2b\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\new xampp\htdocs\b2b\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\new xampp\htdocs\b2b\app\Controllers\Admin.php(103): CodeIgniter\Model->insert(Array)
#8 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(919): App\Controllers\Admin->addvehicle()
#9 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#10 C:\xampp\new xampp\htdocs\b2b\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\new xampp\htdocs\b2b\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-01-01 11:14:47 --> Column 'rgn_date' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `vehicle` (`name`, `rgn_date`, `iddate`, `type`, `number`, `user`, `spi_code`, `rto_exp`, `puc_exp`, `permit_exp`, `insurance_exp`, `fitness_exp`) VALUES (:name:, :rgn_date:, :iddate:, :type:, :number:, :user:, :spi_code:, :rto_exp:, :puc_exp:, :permit_exp:, :insurance_exp:, :fitness_exp:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Admin.php(103): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Admin->addvehicle()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
